# ~/.config/picom/picom.conf
# Configuration file for picom.

# Enable shadows.
shadow = true;

# Set shadow dimensions.
shadow-radius = 0;
shadow-offset-x = 5;
shadow-offset-y = 5;

# Set shadow opacity.
shadow-opacity = 0.5;

# Exclude the following itmes from displaying shadows.
shadow-exclude = [
    "window_type = 'dock'",
    "class_g = 'Dmenu'",
    "name = 'Discord Updater'",
]

# Enable fading.
fading = true;

# Set fading time settings.
fade-delta = 5;
fade-in-step = 0.025;
fade-out-step = 0.025;
