" ~/.vimrc
" Configuration file for vim.

" Enable filetype plugins.
filetype indent plugin on

" Enable syntax highlighting.
syntax on

" Other options.
set autoindent
set number
set incsearch

" Colourscheme.
colorscheme greyscale
