" ~/.vimrc
" Configuration file for vim.

" Enable filetype plugins.
filetype indent plugin on

" Enable syntax highlighting.
syntax on

" Other options.
set autoindent
set number
set incsearch
set foldmethod=marker

set tabstop=4
set shiftwidth=4
set expandtab

" Colourscheme.
colorscheme greyscale

" LaTeX tab sizes.
autocmd FileType tex setlocal shiftwidth=2 softtabstop=2 expandtab
