#!/bin/bash

# ~/.config/bspwm/bspwmrc
# Configuration file for BSPWM, run when it starts.

# Get style.sh for colours and fonts.
source style.sh

# Set screen resolution and DPI.
#xrandr -s 1920x1080
#xrandr --dpi 96

# Basic BSPWM configurations.
bspc config window_gap			0
bspc config border_width 		2

bspc config normal_border_color 	$ACCENT
bspc config active_border_color 	$ACCENT
bspc config focused_border_color 	$FOREGROUND
bspc config presel_feedback_color 	$FOREGROUND

# BSPWM rules for windows.
bspc rule -a floating 			state=floating
bspc rule -a feh 			    state=floating
#bspc rule -a Alacritty          state=pseudo_tiled

# BSPWM mouse configurations.
bspc config pointer_action1		move
bspc config pointer_action2		resize_corner

# Setup monitors and desktops.
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Run extra things.

setxkbmap gb &

numlockx &

picom --backend glx &

notify.sh &

sxhkd &

wallpaper=$(find $HOME/media/images/wallpapers -type l | shuf -n 1)
feh --bg-fill $wallpaper & 

xsetroot -cursor_name left_ptr &

xss-lock -- slock
