#!/bin/bash

source style.sh

bspc config window_gap 15
bspc config border_width 5

bspc config split_ratio 0.5

bspc config normal_border_color $ACCENT
bspc config active_border_color $ACCENT
bspc config focused_border_color $FOREGROUND
bspc config presel_feedback_color $FOREGROUND

if [[ $(xrandr --query | grep DP1-3 | cut -d " " -f 2) == "connected" ]]; then
	bspc monitor eDP1 -n 0 -d 1 2 3 4 5

	xrandr --output DP1-3 --auto --right-of eDP1
	bspc monitor DP1-3 -n 1 -d 6 7 8 9 9 10
else
	bspc monitor eDP1 -n 0 -d 1 2 3 4 5 6 7 8 9 10

	if [[ $(xrandr --query | grep HDMI1 | cut -d " " -f 2) \
		== "connected" ]]; then
		xrandr --output HDMI1 --auto --same-as eDP1
	fi
fi

bspc rule -a feh state=floating
bspc rule -a mpv state=floating
bspc rule -a floating state=floating

setxkbmap gb &

picom &
sxhkd &

feh --bg-fill $(find ~/media/images/wallpapers/ | tail -n +2 | shuf -n 1) &

xss-lock -- slock
