#!/bin/bash

# ~/.config/bspwm/bspwmrc
# Run when BSPWM starts.

# Source style.sh for colours and fonts.
. style.sh

# BSPWM specific settings.
# Set gaps and border width.
bspc config window_gap			15
bspc config border_width		5

# Set default split ratio.
bspc config split_ratio          	0.5

# Set monocle settings.
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true

# Set colours.
bspc config normal_border_color		$ACCENT
bspc config active_border_color		$ACCENT
bspc config focused_border_color	$FOREGROUND
bspc config presel_feedback_color	$FOREGROUND

# Window rules.
bspc rule -a feh state=floating
bspc rule -a mpv state=floating
bspc rule -a floating state=floating

# If external monitor is connected...
if [[ $(xrandr | grep DP1-3 | cut -d " " -f 2) == "connected" ]]; then
	# Setup workspaces on laptop screen.
	bspc monitor eDP1 -n 0 -d 1 2 3 4 5

	# Output and setup workspaces on external monitor
	xrandr --output DP1-3 --auto --right-of eDP1
	bspc monitor DP1-3 -n 1 -d 6 7 8 9 10
else
	# Setup workspaces on laptop screen.
	bspc monitor eDP1 -n 0 -d 1 2 3 4 5 6 7 8 9 10
fi

# Notification system.
notify.sh &

# Set keyboard to use UK layout.
setxkbmap gb &

# Run extra programs.
sxhkd &
picom &

# Wallpaper.
WALLPAPER=$(find ~/media/images/wallpapers | tail -n +2 | shuf -n 1)
feh --bg-fill $WALLPAPER &

# Lockscreen.
xss-lock -- slock
