#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls="ls --color=auto"
alias du="du -h"
alias df="df -h"

PS1="> "
PS2="? "
PS3="# "
PS4="! "

export EDITOR=vim
