# ~/.bashrc
# Run whenever a new bash process is made (e.g. new terminal emulator, etc.).

# If not running interactively, don't do anything.
[[ $- != *i* ]] && return

# Autocompletion scripts.
if [[ -z $ANDROID_ROOT ]]; then
	source /usr/share/bash-completion/bash_completion
fi

# Aliases.
alias cp="cp -r"
alias scp="scp -r"
alias ls="ls --color=auto -v --group-directories-first"
alias du="du -h"
alias df="df -h"
alias tree="tree -v"
alias ssh="TERM=xterm-256color ssh"
alias zathura="zathura --fork"
alias feh="feh --conversion-timeout 1"
alias j="vim -c 'syntax off'"

# Prompts.
PS1="> "
PS2="? "
PS3="# "
PS4="! "

export GPG_TTY=$(tty)
