# ~/.bash_profile
# Run when user logs in.

# Find and source ~/.bashrc.
[[ -f ~/.bashrc ]] && . ~/.bashrc

# Export environment variables.
# Standard environment variables.
export PATH="${PATH}:${HOME}/.bin"

# User environment variables.
export LEDGER_FILE="${HOME}/media/documents/finance/ledger/personal.journal"

# Default programs.
export PAGER=less
export VISUAL=vim
export EDITOR=vim
export BROWSER=qutebrowser

# History file settings.
export HISTFILESIZE=10000
export HISTCONTROL=ignorespace:ignoredups
export HISTTIMEFORMAT="%d/%m/%Y %H:%M:%S "

# Shell options.
shopt -s no_empty_cmd_completion
shopt -s histappend

# Run startx silently.
# This MUST be the last thing in this file - anything after this will not be run on startup.
[[ $(fgconsole 2>/dev/null) == 1 ]] && startx -- vt1 &> /dev/null
