#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

export PATH=$PATH:~/bin

export EDITOR=vim

export HISTFILESIZE=1000
export HISCONTROL=ignorespace:ignoredups
export HISTTIMEFORMAT="%d/%m/%Y %H:%M:%S"

shopt -s no_empty_cmd_completion
shopt -s histappend
